# Generated by Django 2.1.7 on 2019-03-30 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('quantity_name', models.CharField(max_length=80)),
                ('scope', models.CharField(choices=[(None, 'scope default'), ('private', 'Private'), ('public', 'Public')], max_length=80)),
                ('duration', models.DurationField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='counters',
            name='metrics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters_metrics', to='counter.Metrics'),
        ),
        migrations.AddField(
            model_name='counters',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
